#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[ui]
editor = "helix"
default-command = "log"

[user]
name = "InKryption"
email = "inkryption07@gmail.com"

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''

[signing]
behavior = "drop"
backend = "gpg"

[git]
sign-on-push = true

[aliases]
shortlist = ["util", "exec", "--", "sh", "-c", """
jj log -r "$1::$2" --template '" " ++ self.change_id().shortest()' --no-graph --reversed
""", ""]

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = { command = ["delta", "-s"], env = {} }
diff-formatter = ":git"
